ARG NODE_VERSION=17

FROM node:${NODE_VERSION}-alpine

EXPOSE 8080

VOLUME [ "/jasb/client" ]
WORKDIR "/jasb/client"

ENV JASB_DEV_ENV "docker"
ENV NODE_ENV "development"

ENTRYPOINT [ "npm" ]
CMD [ "run", "dev" ]
