name: "jasb"

networks:
  frontend:
  backend:

volumes:
  storage:

services:
  storage:
    image: "postgres:16"
    environment:
      POSTGRES_USER: jasb
      POSTGRES_PASSWORD: jasb
      TZ: UTC
    ports:
      - "127.0.0.1:5432:5432/tcp" # Not needed to run, but allows you to connect to the DB with tooling locally.
    networks:
      - backend
    volumes:
      - storage:/var/lib/postgresql/data
    restart: unless-stopped

  migrate:
    image: "redgate/flyway:9"
    command: migrate
    environment:
      FLYWAY_URL: jdbc:postgresql://storage:5432/jasb
      FLYWAY_USER: jasb
      FLYWAY_PASSWORD: jasb
      FLYWAY_LOCATIONS: filesystem:/flyway/sql/migrations
      FLYWAY_SCHEMAS: jasb
      FLYWAY_CREATE_SCHEMAS: true
    volumes:
      - ../server/src/sql:/flyway/sql
    networks:
      - backend
    depends_on:
      - storage
    restart: no

  tools:
    image: "node:20"
    user: "${USER_ID:?err}:${GROUP_ID:?err}"
    entrypoint: "bash"
    working_dir: "/jasb"
    volumes:
      - ..:/jasb

  server:
    build:
      context: "../server/dev"
    user: "${USER_ID:?err}:${GROUP_ID:?err}"
    environment:
      JASB_CONFIG_PATH: "config.json5;config.dev.json5"
      #ROARR_LOG: true # Log all SQL queries, for debugging.
    volumes:
      - ..:/jasb
    networks:
      - frontend
      - backend

  client:
    build:
      context: "../client/dev"
    user: "${USER_ID:?err}:${GROUP_ID:?err}"
    ports:
      - "127.0.0.1:8080:8080/tcp" # Allows you to connect to the web UI locally.
    volumes:
      - ..:/jasb
    networks:
      - frontend
