name: Build

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up QEMU.
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: GHCR login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v6
        with:
          files: "docker-bake.hcl"
          set: |
            *.output=type=registry
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
        env:
          VCS_REF: ${{ github.sha }}
          VERSION: ${{ github.ref_type == 'tag' && github.ref_name || '' }}
